services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3009:3009" 
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - NODE_ENV=development
    restart: always
    volumes:
      - .:/home/node/app:delegated,Z
      - /home/node/app/node_modules
    depends_on:
      - postgres
    command: npm run start:dev
    networks:
      - app-default

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PORT: ${DB_PORT}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data:Z
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U studyoff -d studyoffdb']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-default

volumes:
  pgdata:

networks:
  app-default:
    driver: bridge
